services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:80"

  home_page:
    build:
      context: ./site
      args:
        VITE_PAGE_URL: https://google.com
    ports:
      - "8081:80"